- app/assets/config/manifest.js
- app/controllers/books_controller.rb
- app/dashboards/book_dashboard.rb
- app/services/sync_service/books.rb
- app/views/admin/books/_form.html.erb
- app/views/admin/books/edit.html.erb
- app/views/layouts/admin/application.html.erb
- app/webpack/administrate/index.js
- app/webpack/css/administrate/application.scss
- app/webpack/packs/administrate.js
- config/database.yml
- config/locales/en.yml
- package.json
- spec/services/xml_books_spec.rb
- spec/services/xml_series_spec.rb
- yarn.lock
> Books: Admin Tabs

- .gitlab-ci.yml
> TWM-115 Gitlab setup

- .gitlab-ci.yml
- Makefile
> Fix invalid gitlab-ci.yml file.

- app/models/book.rb
- app/views/admin/application/_collection.html.erb
- app/views/admin/application/index.html.erb
- app/views/fields/has_many/_show.html.erb
Removes inverse option on has many. 
Removes delete on collection views for models handled by xml harvest
> Book Form Fix

- app/views/fields/subjects_select_field/_form.html.erb
Update condition preventing subject lists from populating.
> Subject List Fix

- app/services/sync_service/books.rb
UTF-16 inserting international characters ad breaking xml ingest. UTF-8 avoids this.
> Update dev xml

- Gemfile
- Gemfile.lock
- Rakefile
- config/webpacker.yml
- package.json
- yarn.lock
Previous force push forgot to commit (empty push)
Force push merged the branch??
update configs as well
> Webpacker 5 update

- .docker/app/Dockerfile
- .docker/ci-app/Dockerfile.ci
Update alpine package and nodejs version
> Dependencies update

- .docker/app/Dockerfile
Add imagemagick package to docker app file.
> ImageMagick in Alpine Image

- .docker/app/Dockerfile
> Imagemagick

- app/models/concerns/imageable.rb
- lib/uploads.rb
Add logging to find cause of infinity error
> Activestorage Image debug

- app/views/books/show.html.erb
- lib/tasks/excerpts.rake
View error fix, and nicer logging.
> Excerpt Tweaks

- app/controllers/admin/books_controller.rb
- app/dashboards/book_dashboard.rb
- app/models/book.rb
- app/views/books/show.html.erb
- lib/tasks/excerpts.rake
Update excerpt harvest to handle bad data, and better reporting. 
Update book show page.
> #TWM-197 Pull excerpts from PressWorks

- app/views/books/show.html.erb
- app/webpack/css/partials/_vars.scss
> #TWM-136_Content model Books front end

- app/controllers/concerns/admin/detachable.rb
- app/views/fields/image_field/_form.html.erb
> Detachable fix

- .docker/app/Dockerfile
- Gemfile
- Gemfile.lock
- app/models/book.rb
- app/models/oabook.rb
- app/models/person.rb
- app/models/series.rb
- app/models/special_offer.rb
- app/models/subject.rb
- app/views/admin/books/_form.html.erb
- package.json
- yarn.lock
Add activestorage validator gem. 
Add validations to models. 
Custom book form updated when errors present due to lack of instance variable instantiations.
> ActiveStorage Validations

- db/migrate/20210608182842_create_agencies.rb
Resolve db issue introduced by manual migration edit
> #TWM-133 Content model: Agencies front end display

- .docker/ci-app/Dockerfile.ci
- Gemfile
- Gemfile.lock
- app/controllers/people_controller.rb
- app/dashboards/person_dashboard.rb
- app/views/people/index.html.erb
- app/views/people/show.html.erb
- app/webpack/css/books.scss
- db/migrate/20210614130317_add_head_field_to_person.rb
- db/schema.rb
- lib/uploads.rb
- package.json
- spec/factories/person.rb
- spec/features/people_spec.rb
- yarn.lock
Adds dept head ordering
Orderly gem for testing element position on page
> #TWM-210 updates to people page

- app/views/devise/sessions/new.html.erb
> #TWM-207 Footer access to admin interface

- .gitignore
- app/controllers/admin/catalogs_controller.rb
- app/controllers/books_controller.rb
- app/controllers/catalogs_controller.rb
- app/controllers/concerns/admin/detachable.rb
- app/dashboards/book_dashboard.rb
- app/dashboards/catalog_dashboard.rb
- app/helpers/application_helper.rb
- app/helpers/catalogs_helper.rb
- app/models/book.rb
- app/models/catalog.rb
- app/services/sync_service/catalogs.rb
- app/views/books/show.html.erb
- app/views/catalogs/index.html.erb
- app/views/catalogs/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/catalogs_controller_spec.rb
- spec/factories/book.rb
- spec/models/catalog_spec.rb
- spec/services/xml_catalogs_spec.rb
- spec/views/catalogs/index.html.erb_spec.rb
- spec/views/catalogs/show.html.erb_spec.rb
Adds in views, controller updates, and tests
> Catalog displays

- .docker/app/Dockerfile
Update mariadb, libxslt, and shared-mime-info for K8 deploy.
> Docker updates

- .docker/app/Dockerfile
- .gitlab-ci.yml
* use docker-20
* Revert "Pin harbor ruby container version."
This reverts commit dcd26fa9fcfef98ad59741400ce658c313672b8f.
> Unpin rails docker container.

- app/helpers/application_helper.rb
- app/views/conferences/index.html.erb
- app/views/oabooks/_ls_book_list.html.erb
- app/views/oabooks/labor_studies.html.erb
- app/views/oabooks/north_broad_press.html.erb
- spec/controllers/oabook_controller_spec.rb
- spec/support/index_editable_spec.rb
update view templates for labor studies collection
> Oabooks display: fix

- app/controllers/conferences_controller.rb
- app/views/conferences/index.html.erb
- app/webpack/css/conferences.scss
> #TWM-183 Content model frontend: Conferences

- app/webpack/css/administrate/application.scss
- app/webpack/css/main.scss
Hide captions under trix images
> Trix Captions

- app/controllers/catalogs_controller.rb
- app/controllers/subjects_controller.rb
- app/views/books/_alphamenu.erb
- app/views/books/_books.html.erb
- app/views/books/index.html.erb
- app/views/books/show.html.erb
- app/views/catalogs/show.html.erb
- app/views/subjects/index.html.erb
- app/views/subjects/show.html.erb
- app/webpack/css/application.scss
- app/webpack/css/subjects.scss
- config/routes.rb
- spec/requests/subjects_spec.rb
- spec/views/catalogs/show.html.erb_spec.rb
**note**: extracts book list template from books and reuses across books, catalogs, and subjects.
> #TWM-218 create subject show page

- .docker/app/Dockerfile
> #TWM-217 Create Subjects Index View

- .docker/app/Dockerfile
update dockerfile to nodejs=14.17.4-r0
> Nodejs Update

- app/helpers/events_helper.rb
> #TWM-230 Create Events Calendar

- app/controllers/catalogs_controller.rb
- app/controllers/subjects_controller.rb
- app/controllers/webpages_controller.rb
- app/dashboards/catalog_dashboard.rb
- app/dashboards/subject_dashboard.rb
- app/helpers/webpages_helper.rb
- app/models/brochure.rb
- app/models/catalog.rb
- app/models/subject.rb
- app/views/catalogs/show.html.erb
- app/views/fields/has_many/_form.html.erb
- app/views/subjects/show.html.erb
- app/views/webpages/index.html.erb
- app/webpack/css/homepage.scss
- db/migrate/20210915165206_add_brochures_to_models.rb
- db/schema.rb
- spec/controllers/subjects_controller_spec.rb
- spec/factories/brochure.rb
- spec/factories/catalog.rb
- spec/helpers/webpages_helper_spec.rb
- spec/models/brochure_spec.rb
- spec/models/catalog_spec.rb
- spec/models/subject_spec.rb
First part of homepage functionality, second part will follow in separate PR.
This pr includes:
- highlights carousel
- Top news section
- Catalog callout
- Brochure callout
also includes necessary brochure work for subjects and catalogs.
> #TWM-231 homepage functionality

- .gitlab-ci.yml
* Stage name must be specific gitlab name not custom.
> Update stage name.

- .docker/app/Dockerfile
> #TWM-285 Cover Images

- .gitignore
- app/controllers/application_controller.rb
- app/controllers/books_controller.rb
- app/controllers/webpages_controller.rb
- app/dashboards/book_dashboard.rb
- app/helpers/books_helper.rb
- app/models/author.rb
- app/models/book.rb
- app/models/concerns/friendable.rb
- app/models/special_offer.rb
- app/services/sync_service/authors.rb
- app/services/sync_service/books.rb
- app/views/authors/show.html.erb
- app/views/books/awards_by_subject.html.erb
- app/views/books/awards_by_year.html.erb
- app/views/fields/see_also_field/_form.html.erb
- app/views/fields/select/_form.html.erb
- app/webpack/css/books.scss
- bin/rails
- bin/rake
- bin/spring
- lib/tasks/import_json_authors.rake
- lib/tasks/import_json_books.rake
- lib/tasks/import_json_special_offers.rake
- spec/factories/book.rb
- spec/models/book_spec.rb
- spec/requests/books_spec.rb
- spec/services/xml_authors_spec.rb
- spec/services/xml_books_spec.rb
Adds books and author importers
Updates statuses
Reworks subjects
Updates awards
Slug sequence only if one or more exist
> #TWM-288 tupress new site misc items

- app/models/author.rb
- app/models/book.rb
- app/models/conference.rb
- app/models/event.rb
- app/models/faq.rb
- app/models/journal.rb
- app/models/oabook.rb
- app/models/person.rb
- app/models/series.rb
- app/models/subject.rb
- app/models/webpage.rb
remove trailing space in query
**note**: strip did not remove trailing space
> #TWM-288 TUPRESS NEW SITE: Misc items

- .docker/app/Dockerfile
- app/dashboards/book_dashboard.rb
- app/helpers/books_helper.rb
- app/views/books/show.html.erb
- spec/factories/book.rb
- spec/helpers/books_helper_spec.rb
Adds suppress method
Removes order button for OP status
> #TWM-286 title index and author index

- app/controllers/books_controller.rb
- app/controllers/forms_controller.rb
- app/views/books/show.html.erb
- app/views/forms/copy-request/_intro.html.erb
- app/views/forms/copy-request/_request-info.html.erb
- app/webpack/css/main.scss
- app/webpack/css/partials/_navigation.scss
- app/webpack/css/partials/_vars.scss
- config/locales/en.yml
- config/routes.rb
- spec/requests/forms/copy_request_spec.rb
Adds functionality linking book show page to copy-request form.
Fills in selected book automatically.
> TWM-363 new website examination copy request form

- .docker/app/Dockerfile
- app/helpers/events_helper.rb
- spec/helpers/events_helper_spec.rb
> TWM-374 new-website-events-page-time

- .docker/app/Dockerfile
- .gitlab-ci.yml
- Gemfile.lock
- yarn.lock
> Security updates

- Gemfile
> Mail Gem Workaround

- app/views/series/show.html.erb
> TWM-284-series-pages

- bin/xml-ingest.sh
Rails sync of xml files manual upload to prod
> Xml ingest

- db/migrate/20220506161540_add_featured_award_weight_field_to_books.rb
Recently updated migration cleanup missed this migration.
> TWM-378-new-website-awards-featured-books

- app/views/admin/application/_collection.html.erb
- app/views/catalogs/_books.html.erb
- app/views/catalogs/show.html.erb
Also removes Destroy from admin catalog collection view.
> TWM-414 new-website-adding-catalog-covers

- app/webpack/css/main.scss
- app/webpack/css/webpages.scss
TWM-406: make gold style available globally
> TWM-406-new-website-resources-for-booksellers-page

- app/views/books/_cover_image.html.erb
> TWM-332 Alt Text for Images

- app/controllers/books_controller.rb
- app/controllers/forms_controller.rb
- app/controllers/webpages_controller.rb
- app/dashboards/book_dashboard.rb
- app/models/author.rb
- app/models/book.rb
Adds filter to search results
Adds isbn field to search
> Twm 426 suppressed books

- .docker/app/Dockerfile
- app/assets/stylesheets/partials/_header.scss
- app/controllers/books_controller.rb
- app/controllers/webpages_controller.rb
- app/views/application/_header_navbar.html.erb
- app/views/layouts/application.html.erb
- config/environments/production.rb
This leaves only the Informational email address issue unaddressed.
We should ask for another review to check the changes work as intended.
> Twm 443 review security scan

- config/environments/production.rb
Adds secure cookies and Strict-Transport-Security headers to the
production environment but does not force redirect to SSL.
The Ingress handles forcing a redirect to SSL.
> TWM-443: Secure Cookies.

- app/services/sync_service/authors.rb
- app/services/sync_service/book_series.rb
- app/services/sync_service/books.rb
- app/services/sync_service/catalogs.rb
- app/services/sync_service/reviews.rb
- app/services/sync_service/subjects.rb
- spec/services/xml_reviews_spec.rb
- spec/services/xml_subjects_spec.rb
ELK logging needed better clarity and consistency across models.
> Refactor syncs for better logging

- .gitlab-ci.yml
> Update prod helm chart version (0.3.2).

- app/assets/stylesheets/forms.scss
- app/javascript/controllers/desk_exam_controller.js
- app/views/forms/copy-request/_request-info.html.erb
- config/locales/en.yml
revert changes to form options, add price note to exam hard copies only
> TWM-363 Examination Copy Request Form

- .gitlab-ci.yml
> Update helm chart version to 0.3.3

- app/controllers/subjects_controller.rb
- app/models/book.rb
- config/database.yml
- spec/features/subjects_spec.rb
Filter to include 1999, update tests
> #TWM-393 new website sorting by year showing most recent

- app/views/admin/application/_collection.html.erb
Rails/UJS removed, new method turbo.
> #TWM-420 searches/events

- .gitlab-ci.yml
> Update helm version (0.3.5)

- .gitlab-ci.yml
> TWM-454 Announcing new series on series listing page

- app/javascript/application.js
> TWM-430 add-google-analytics

- app/helpers/books_helper.rb
- spec/helpers/books_helper_spec.rb
formats are sometimes singular
> Isbn update

- .docker/app/Dockerfile
- app/views/books/_books.html.erb
- app/views/catalogs/_books.html.erb
> TWM-470 urgent shopping cart issue

- .gitlab-ci.yml
- docker-compose.yaml
> update chart version

- config/environments/production.rb
Reverts tulibraries/Press-6#673
> Revert "Try using a different log path"

- app/dashboards/book_dashboard.rb
- app/services/sync_service/authors.rb
- app/services/sync_service/book_series.rb
- app/services/sync_service/books.rb
- app/services/sync_service/catalogs.rb
- app/services/sync_service/reviews.rb
- app/services/sync_service/subjects.rb
- app/views/admin/application/_collection_items_action.html.erb
- app/views/admin/books/edit.html.erb
- app/views/admin/people/_form.html.erb
Also prevents stdout from sync services filling up rspec output
> TWM-500 clear up administrate deprecation warnings

- .docker/app/Dockerfile
- Makefile
> Add jemalloc and enable web concurrency.

- config/environments/production.rb
This fixes a deprecation in the logging system as of rails 7.1 where Logger no longer has a broadcast method. BroadcastLogger was implemented to replace that private functionality. 
Note: there is a current bug in railties that prevents separate log levels for the different sinks in the broadcast. It was attempted to be addressed here: https://github.com/rails/rails/pull/50337/files but as of 7.2.2.1 there have been changes to that, specifically https://github.com/rails/rails/blob/main/railties/lib/rails/application/configuration.rb:395 where the broadcast_log_level method was changed to an attr_reader. 
All logs will remain at level 1 (:info).
> TWM-525 upgrade rails to version 7.2.2.1

- app/dashboards/event_dashboard.rb
- app/dashboards/news_item_dashboard.rb
- app/helpers/application_helper.rb
- app/helpers/webpages_helper.rb
- app/views/application/_carousel.html.erb
- app/views/books/_books.html.erb
- app/views/books/_cover_image.html.erb
- app/views/books/_featured_awards.html.erb
- app/views/catalogs/_books.html.erb
- app/views/oabooks/_cover_image.html.erb
- app/views/oabooks/_ls_book_list.html.erb
- app/views/oabooks/_nb_book_list.html.erb
- app/views/people/_image_link.html.erb
- app/views/series/show.html.erb
- app/views/webpages/index.html.erb
- app/views/webpages/search/_book_results.html.erb
- config/locales/en.yml
- db/migrate/20250519150256_add_image_alt_text_to_news_item.rb
- db/migrate/20250519152202_add_image_alt_text_to_event.rb
- db/schema.rb
- spec/helpers/books_helper_spec.rb
- spec/helpers/webpages_helper_spec.rb
Images with manually supplied alt text will take precedence.
> Auto alt text for images

- app/controllers/webpages_controller.rb
https://app.honeybadger.io/projects/84285/faults/121541831
> make redirect work

- Gemfile
- Gemfile.lock
- Log on startup states "You don't have rexml installed in your application. Please add it to your Gemfile and run bundle install"
> Fixes error starting sync-delta failure
